
stages:
    - deps
    - check
    - build
    - deploy
    
cache:
  paths:
    - /root/.cache/composer/

vendor:
    stage: deps
    image: cyberpearuk/php-build-docker
    script:
        - composer global config http-basic.nexus.jbuncle.co.uk composer-publisher $NEXUS_PASS 
        - composer install
    artifacts:
        expire_in: 1 day
        paths:
            - vendor/
    only:
        refs:
            - branches
      
phpcs:
    stage: check
    image: cyberpearuk/php-build-docker
    dependencies:
        - vendor
    script:
        - vendor/bin/phpcs -n -s --standard=./ruleset.xml ./src
    only:
        refs:
            - branches

phan:
    stage: check
    image: jbuncle/php-build-phan
    dependencies:
        - vendor
    script:
        - phan --target-php-version=7.4
        - phan --target-php-version=8.0
    only:
        refs:
            - branches

version:
    stage: build
    image: jbuncle/php-autosemver
    dependencies: []
    script:
        - echo "VERSION=$(next-version)" >> build.env
        - cat build.env
    artifacts:
        reports:
            dotenv: build.env
    only:
        refs:
            - master

tag:
    stage: deploy
    image: jbuncle/php-autosemver
    needs:
        - job: version
          artifacts: true
    script:
        - git-tag ${VERSION}
    only:
        refs:
            - master

deploy_tag:
    stage: deploy
    image: jbuncle/composer-nexus-upload
    needs:
        - job: version
          artifacts: true
    script:
        - nexus-upload
         --repository=https://nexus.jbuncle.co.uk/repository/composer-private/ 
         --username=composer-publisher 
         --password=$NEXUS_PASS 
         --version=${VERSION}
         --ignore="/^(nbproject.*|\.gitlab\-ci\.yml)$/"
    only:
        refs:
            - master
