
stages:
    - deps
    - check
    - build
    - version
    - pack
    - release

cache:
    - key: composer-cache
      paths:
        - /root/.cache/composer/
        - /root/.composer/cache
      policy: pull-push
      
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - vendor
      policy: pull-push

phan:
    stage: check
    image: jbuncle/php-build-phan
    only:
        refs:
            - branches
    before_script:
        - composer global config github-oauth.github.com $GITHUB_TOKEN 
        - composer global config http-basic.nexus.jbuncle.co.uk composer-publisher $NEXUS_PASS 
        - composer install --ignore-platform-reqs --prefer-dist
    script:
        - phan --target-php-version=7.4
        - phan --target-php-version=8.0

phpcs:
    stage: check
    image: cyberpearuk/php-build-docker
    only:
        refs:
            - branches
    before_script:
        - composer global config github-oauth.github.com $GITHUB_TOKEN 
        - composer global config http-basic.nexus.jbuncle.co.uk composer-publisher $NEXUS_PASS 
        - composer install --ignore-platform-reqs --prefer-dist
    script:
        - vendor/bin/phpcs -n -s --standard=php-standards ./src
        - vendor/bin/phpcs -n -s --standard=php-standards ./tests

phpunit:
    stage: check
    image: cyberpearuk/php-build-docker
    only:
        refs:
            - branches
    before_script:
        - composer global config github-oauth.github.com $GITHUB_TOKEN 
        - composer global config http-basic.nexus.jbuncle.co.uk composer-publisher $NEXUS_PASS 
        - composer install --ignore-platform-reqs --prefer-dist
    script:
        - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'

version:
    stage: version
    image: jbuncle/php-autosemver
    needs:
        - job: phpcs
          artifacts: false
        - job: phan
          artifacts: false
        - job: phpunit
          artifacts: false
    script:
        - echo "VERSION=$(next-version)" >> build.env
        - cat build.env
    artifacts:
        reports:
            dotenv: build.env
    only:
        refs:
            - master

git-tag:
    stage: release
    image: jbuncle/php-autosemver
    needs:
        - job: version
          artifacts: true
    script:
        - git-tag ${VERSION}
    only:
        refs:
            - master

nexus-publish:
    stage: release
    image: jbuncle/composer-nexus-upload
    needs:
        - job: version
          artifacts: true
    script:
        - nexus-upload
         --repository=https://nexus.jbuncle.co.uk/repository/composer-private/ 
         --username=composer-publisher 
         --password=$NEXUS_PASS 
         --version=${VERSION}
         --ignore="/^(vendor|nbproject|\.gitlab\-ci\.yml|\.phan|tests|phpunit\.xml)/"
    only:
        refs:
            - master
